### ISSUE TITLE
After muting and changing difficulty this error shows up

### ISSUE THREAD

**Issue by DemonSpeed** [EnriqueMoran/google-minesweeper-bot#1]
Traceback (most recent call last):
  File "C:\Users\Me\OneDrive\Desktop\AutoPiano\google-minesweeper-bot-master\minesweeper.py", line 430, in <module>
    minesweeper.play()
  File "C:\Users\Me\OneDrive\Desktop\AutoPiano\google-minesweeper-bot-master\minesweeper.py", line 386, in play
    self.gameWindow = self.getGameWindow()
  File "C:\Users\Me\OneDrive\Desktop\AutoPiano\google-minesweeper-bot-master\minesweeper.py", line 56, in getGameWindow
    im2, contours, hierarchy = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by DO-Ui** [comment]
According to the OpenCV Docs, this function only returns 2 values, this most likely broke due to an OpenCV update. Try installing an older version of OpenCV. Maybe try OpenCV version 3.2 as it seems to be the last version that returns 3 values.
https://docs.opencv.org/4.4.0/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0

**Comment by ckosk** [comment]
What worked for me without changing OpenCV versions was changing line 56 in minesweeper.py from:
```python
im2, contours, hierarchy = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
```
To:
```python
contours, hierarchy = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
```

**Comment by bensonnlee** [comment]
made a bot that should work!

https://github.com/bensonnlee/google-minesweeper-bot
