### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by RavenVR** [EnriqueMoran/google-minesweeper-bot#3]
once i run the program, it says this:
`To stop this script place the mouse on top-left corner of the screen.
Mute sound button not found! (might be already muted)
Traceback (most recent call last):
  File "C:\Users\s12073\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 116, in setDifficulty
    configButton = pyautogui.locateOnScreen(self.configImage, confidence=0.9)
  File "C:\Users\s12073\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\s12073\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "C:\Users\s12073\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze\__init__.py", line 372, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "C:\Users\s12073\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze\__init__.py", line 144, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s12073\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 430, in <module>
    minesweeper.play()
  File "C:\Users\s12073\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 384, in play
    self.setDifficulty()
  File "C:\Users\s12073\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 129, in setDifficulty
    raise Exception("Flag image not found!")
Exception: Flag image not found!`
even if i focus on the google window

**Comment by yodaluca23** [comment]
It says this for me:

To stop this script place the mouse on top-left corner of the screen.
Mute sound button not found! (might be already muted)
Traceback (most recent call last):
  File "D:\yodal\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 430, in <module>
    minesweeper.play()
  File "D:\yodal\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 386, in play
    self.gameWindow = self.getGameWindow()
  File "D:\yodal\Downloads\google-minesweeper-bot-master\google-minesweeper-bot-master\minesweeper.py", line 56, in getGameWindow
    im2, contours, hierarchy = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by bensonnlee** [comment]
made a version that should work!

https://github.com/bensonnlee/google-minesweeper-bot
